### ISSUE TITLE
Search places by name.

### ISSUE THREAD

**Issue by priyanshsaxena** [ankita132/react_google_map#11]
Add a search box to let users search locations by name. I shall be glad to be assigned to work on this, and any ideas regarding this are welcome. @ankita132 please assign this issue to me, and add 'feature-request' and any other suitable labels.

**Comment by priyanshsaxena** [comment]
@ankita132 I have added a PR for this issue. Please review it.

**Comment by ankita132** [comment]
fixed in #13
