### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by ankita132** [ankita132/react_google_map#15]
add which packages need to be installed while running the app using npm

**Comment by ubarsaiyan** [comment]
On running npm start it gives the following error "Module not found: Can't resolve 'firebase' in '/home/utkarsh/Downloads/react_google_map/src/components'"

**Comment by ankita132** [comment]
thats what i am saying. For that you need to install firebase , sweetalert2 and other important packages. In the readme i want the instructions what all packages to be installed

**Comment by priyanshsaxena** [comment]
We can probably add it to the package.json file itself. The required versions are 4.8.0 for Firebase and 7.0.9 for SweetAlert2. The assignee should install the required packages using npm install --save firebase, and then update both the package.json and the package-lock.json file. However, there will be hundreds of merge-conflicts for package-lock.json file this way.

Another way is to try and update just the dependencies section in package.json file. The required section will then read:
```
"dependencies": {
    "firebase": "^4.8.0",
    "google-map-react": "^0.24.0",
    "google-maps": "^3.2.1",
    "lodash": "^4.17.4",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-firebase-file-uploader":"^2.4.1",
    "react-google-map": "^3.0.1",
    "react-google-maps": "^6.3.0",
    "sweetalert2": "^7.0.9"
  }
```

Can anyone else confirm if making just this one change after cloning the repository fixes the issue ?

**Comment by ankita132** [comment]
can be done definitely

**Comment by priyanshsaxena** [comment]
The three commands that need to be run after cloning the repository now are:

```
sudo npm install --save firebase
sudo npm install --save react-firebase-file-uploader
sudo npm install --save sweetalert2
```
