### ISSUE TITLE
upload and store images in firebase

### ISSUE THREAD

**Issue by ankita132** [ankita132/react_google_map#4]

**Comment by abhishek71994** [comment]
I'll be trying to work on this one. If no one is working on it?

**Comment by ankita132** [comment]
sure @abhishek71994 . go for it

**Comment by priyanshsaxena** [comment]
I have worked this out. @ankita132 you might need to add me as a contributor for me to commit to it.

**Comment by ankita132** [comment]
@priyanshsaxena you need to send a pull request to the repository.No need of adding anyone as the contributer.

**Comment by priyanshsaxena** [comment]
@ankita132 I have created a pull request as directed.

**Comment by ankita132** [comment]
fixed in #10
